package main

import (
	"context"
	"errors"
	"fmt"
	htmlpkg "html"
	"io"
	"math/rand"
	"net/http"
	"net/url"
	"regexp"
	"strings"
)

type NetInfo struct {
	SSID      string
	Interface string
	UUID      string

	// Client's DNS is pinned to the Wi-Fi interface's own nameserver, so
	// captive-portal hostnames resolve even when the system resolver is
	// pinned elsewhere (VPN, DoH).
	Client *http.Client
}

type Handler struct {
	Login func(ctx context.Context, info NetInfo) error
	// Metered, if true, sets connection.metered=yes on the NM profile.
	Metered bool
}

var handlers = map[string]Handler{
	"NormandieTrainConnecte": {Metered: true, Login: normandieTrainConnecte},
	"_SNCF_WIFI_INOUI":       {Metered: true, Login: sncfInoui},
	"*WIFI-AIRPORT":          {Metered: true, Login: parisAeroport},
}

func normandieTrainConnecte(ctx context.Context, info NetInfo) error {
	return sncfActivate(ctx, info, "wifi.normandie.fr", "{}")
}

func sncfInoui(ctx context.Context, info NetInfo) error {
	return sncfActivate(ctx, info, "wifi.sncf", "{}")
}

// sncfActivate POSTs an activation request to the shared VSCT/SNCF portal
// API used by multiple SNCF train Wi-Fi networks.
func sncfActivate(ctx context.Context, info NetInfo, host, body string) error {
	url := "https://" + host + "/router/api/connection/activate/auto"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, strings.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := info.Client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	io.Copy(io.Discard, resp.Body)

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("status %d", resp.StatusCode)
	}
	return nil
}

// parisAeroport walks the Hub One captive portal funnel for Paris airports
// (CDG / Orly, "*WIFI-AIRPORT"). The FortiGate gateway intercepts HTTP and
// redirects to a multi-page welcome flow that requires filling in a fake
// name/email; the last page hands us a form pre-populated with the actual
// FortiGate auth credentials, which we POST to flip the gate.
func parisAeroport(ctx context.Context, info NetInfo) error {
	// 1. Trigger the FortiGate redirect. Any HTTP URL works; detectportal
	//    is what NM already probed. Following redirects lands us on
	//    welcome.php with PHPSESSID set and `magic` associated to it.
	page, cur, err := hubOneGet(ctx, info.Client, "http://detectportal.firefox.com/success.txt")
	if err != nil {
		return err
	}

	// 2. Frequency form.
	page, cur, err = hubOnePost(ctx, info.Client, cur, url.Values{
		"freqForm_token": {extractHiddenInput(page, "freqForm_token")},
		"frequency_form": {"isset"},
		"btnSubmitFreq":  {""},
	})
	if err != nil {
		return err
	}

	// 3. Personal info form (fake data).
	page, cur, err = hubOnePost(ctx, info.Client, cur, url.Values{
		"full_token": {extractHiddenInput(page, "full_token")},
		"sex":        {"mr"},
		"lastname":   {randAZ(8)},
		"mail":       {randAZ(8) + "@" + randAZ(6) + ".com"},
		"cond":       {"on"},
	})
	if err != nil {
		return err
	}

	// 4. Advertising page acknowledgement.
	page, _, err = hubOnePost(ctx, info.Client, cur, url.Values{
		"pubForm": {"pubForm"},
	})
	if err != nil {
		return err
	}

	// 5. gateway.php returns a form pre-filled with the FortiGate auth
	//    credentials generated by Hub One for this session.
	fgAction := extractFormAction(page)
	if fgAction == "" {
		return errors.New("gateway.php: no FortiGate form")
	}
	fgURL, err := url.Parse(fgAction)
	if err != nil {
		return err
	}
	_, _, err = hubOnePost(ctx, info.Client, fgURL, url.Values{
		"magic":    {extractHiddenInput(page, "magic")},
		"4Tredir":  {extractHiddenInput(page, "4Tredir")},
		"username": {extractHiddenInput(page, "username")},
		"password": {extractHiddenInput(page, "password")},
	})
	return err
}

func hubOneGet(ctx context.Context, client *http.Client, rawURL string) ([]byte, *url.URL, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Accept", "text/html,application/xhtml+xml")
	resp, err := client.Do(req)
	if err != nil {
		return nil, nil, err
	}
	body, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, nil, fmt.Errorf("GET %s: status %d", rawURL, resp.StatusCode)
	}
	return body, resp.Request.URL, nil
}

func hubOnePost(ctx context.Context, client *http.Client, u *url.URL, form url.Values) ([]byte, *url.URL, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), strings.NewReader(form.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "text/html,application/xhtml+xml")
	resp, err := client.Do(req)
	if err != nil {
		return nil, nil, err
	}
	body, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, nil, fmt.Errorf("POST %s: status %d", u.String(), resp.StatusCode)
	}
	return body, resp.Request.URL, nil
}

// extractHiddenInput finds the HTML-unescaped value of `<input ... name="<name>"
// ... value="..." ...>` in the given HTML.
func extractHiddenInput(page []byte, name string) string {
	re := regexp.MustCompile(`<input[^>]*name="` + regexp.QuoteMeta(name) + `"[^>]*value="([^"]*)"`)
	m := re.FindSubmatch(page)
	if m == nil {
		return ""
	}
	return htmlpkg.UnescapeString(string(m[1]))
}

func extractFormAction(page []byte) string {
	re := regexp.MustCompile(`<form[^>]*action="([^"]+)"`)
	m := re.FindSubmatch(page)
	if m == nil {
		return ""
	}
	return htmlpkg.UnescapeString(string(m[1]))
}

func randAZ(n int) string {
	const letters = "abcdefghijklmnopqrstuvwxyz"
	b := make([]byte, n)
	for i := range b {
		b[i] = letters[rand.Intn(len(letters))]
	}
	return string(b)
}
